import pandas as pd
from src.database.connection import get_db_connection

# Force pandas to show all columns beautifully without squishing them
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

def inspect_database():
    engine = get_db_connection()
    
    print("\n" + "🛡️ " * 15)
    print("   GRIDWISE VAULT MASTER INSPECTION")
    print("🛡️ " * 15 + "\n")

    # --- PART 1: THE INVENTORY (High-Level Stats) ---
    print("📊 PART 1: DATABASE INVENTORY (Timeline & Counts)")
    query_inventory = """
        SELECT 
            price_area,
            MIN(ds) as oldest_record,
            MAX(ds) as newest_record,
            COUNT(*) as total_hours
        FROM historical_training_data
        GROUP BY price_area;
    """
    try:
        df_inv = pd.read_sql(query_inventory, engine)
        print("-" * 65)
        for _, row in df_inv.iterrows():
            print(f"Area: {row['price_area']}")
            print(f"  Oldest Record: {row['oldest_record']}")
            print(f"  Newest Record: {row['newest_record']}")
            print(f"  Total Hours:   {row['total_hours']}")
            print("-" * 65)
    except Exception as e:
        print(f"Inventory Error: {e}")

    # --- PART 2: PEEK AT HISTORICAL DATA (The Past) ---
    print("\n📦 PART 2: PEEK INSIDE 'historical_training_data'")
    print("Showing the 5 most recently ingested actuals for DK1...")
    print("-" * 65)
    try:
        df_hist = pd.read_sql("SELECT * FROM historical_training_data WHERE price_area='DK1' ORDER BY ds DESC LIMIT 5", engine)
        print(df_hist)
    except Exception as e:
        print(f"Historical Peek Error: {e}")

    # --- PART 3: PEEK AT FORECAST DATA (The Future) ---
    print("\n🔮 PART 3: PEEK INSIDE 'forecast_results'")
    print("Showing the 5 most recent predictions generated by XGBoost...")
    print("-" * 65)
    try:
        df_fore = pd.read_sql("SELECT * FROM forecast_results WHERE price_area='DK1' ORDER BY forecast_time DESC LIMIT 5", engine)
        print(df_fore)
    except Exception as e:
        # If the table doesn't exist yet, it just catches gracefully
        print(f"Forecast Peek Error: {e}")
        
    print("\n✅ Master Inspection complete! Vault is secure.\n")

if __name__ == "__main__":
    inspect_database()