services:
  app:
    container_name: greenhour-guardian-app
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8501:8501"

    env_file:
      - .env

    volumes:
      - .:/app

    restart: unless-stopped